[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

# This flag helps with debugging Wi-Fi/I2C issues under the hood
build_flags = -DCORE_DEBUG_LEVEL=3

lib_deps =
    mathworks/ThingSpeak @ ^2.0.0
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit BME280 Library @ ^2.2.4  # Common "Smart" sensor
    adafruit/Adafruit BusIO @ ^1.16.1          # Required for many I2C sensors
    Wire                                       # Essential for I2C